### PR TITLE
Update Assembly Version

### PR DESCRIPTION
**Pull request by BHoMBot**
Updates Assembly Version to 4.3

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Approved from a CI/CD perspective.

**Review by alelom — APPROVED** [review]

**Review by IsakNaslundBh — APPROVED** [review]
LGTM!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check versioning
@BHoMBot check serialisation
@BHoMBot check null-handling
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
