### PR TITLE
Fix distinct causes assigned properties to be lost

### LINKED ISSUE #126: BHoM_Adapter: Distinct method in Replace causes assigned properties of coincident objects to be lost
#### Description:

The Replace method in the BHoM_Adapter uses the `Enumerable.Distinct` method to cull duplicates using a comparer. If you push two lines that share a node, with one node being assigned a property, then that property will be lost when the lines are pushed.

#### How to replicate:

1. Create two `Point `objects and a `Line`, that shares a `Point `with one of the existing `Point`
2. Create a `Bar `using the defined line
3. Create a `Constraint6DOF `
4. Create two `Node `objects using the `Point `objects, and assign the support to the `Node `that is conicident with the `Bar`
5. Create a `Bar `from the two `Node `objects
6. Push both `Bar `objects using the same Push component

#### Expected behaviour:

When pushing the two `Bar `objects described above, the BHoM_Adapter should recognise that the `Node `objects have the same position but different properties and merge them. 

This does raise the question about the scenario when the two `Node `objects have differing `Constraint6DOF `objects assigned. 

#### Test file(s):

https://burohappold.sharepoint.com/:f:/s/BHoM/ErI9qiifV1NMhuiwH548i8UBamTci0e45pNA1XuJGPDOMA?e=qNFYUY

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #126 

Finally fixing this old issue of better handling merging of properties on "same" object being pushed in, most common case being highlighted in the issue (Node with and without constraints).

Done by instead of call to Distinct, a call to GroupBy is made, after CopyBHoMProperties and any CopyPropertiesModules is called, making sure all relevant properties are merged over.

Also, update to how the ID assignment from any duplicate objects is made, as simply can rely on the group, rather then trying to re-fetch from the list based on another call with the comparer. This should be a bit more efficient than previous implementation.

### Test files

Have added new PushTest doing exactly what is highlighted in the issue. Was failing before, but working after changes.

Also, added a new test to check that all pushed objects have ids assigned. Was working before as well, but wanted to add this additional case as I made some changes to how it was handled.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Review by alelom — APPROVED** [review]
Approving based on review of code changes and unit-tests. The code changes make sense and effectively fix a problem introduced by the ["push at the same time" feature](https://github.com/BHoM/BHoM_Adapter/pull/332). Unit tests cover this fix well.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
