### PR TITLE
Adding recorderror message to the default Execute method

### LINKED ISSUE #207: Add `RecordError` saying "not implemented" to the default Execute action
#### Description:

As title. So people do not need to override the Execute only to say "not implemented".

This:
```cs
public virtual Output<List<object>, bool> Execute(IExecuteCommand command, ActionConfig actionConfig = null)
{
      return new Output<List<object>, bool> { Item1 = null, Item2 = false};
}
```

should become

```cs
public virtual Output<List<object>, bool> Execute(IExecuteCommand command, ActionConfig actionConfig = null)
{
     BH.Engine.Reflection.Compute.RecordError($"Execute is not implemented in {this.GetType().Name}.");

     return new Output<List<object>, bool> { Item1 = null, Item2 = false};
}
```

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #207

### Test files

<details> 
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Archive name="Root">
  
  
  
  <items count="1">
    <item name="ArchiveVersion" type_name="gh_version" type_code="80">
      <Major>0</Major>
      <Minor>2</Minor>
      <Revision>2</Revision>
    </item>
  </items>
  <chunks count="1">
    <chunk name="Clipboard">
      <items count="1">
        <item name="plugin_version" type_name="gh_version" type_code="80">
          <Major>1</Major>
          <Minor>0</Minor>
          <Revision>7</Revision>
        </item>
      </items>
      <chunks count="5">
        <chunk name="DocumentHeader">
          <items count="5">
            <item name="DocumentID" type_name="gh_guid" type_code="9">3af2bd3f-3481-4c36-86c2-ae08e5a9c947</item>
            <item name="Preview" type_name="gh_string" type_code="10">Shaded</item>
            <item name="PreviewMeshType" type_name="gh_int32" type_code="3">1</item>
            <item name="PreviewNormal" type_name="gh_drawing_color" type_code="36">
              <ARGB>100;150;0;0</ARGB>
            </item>
            <item name="PreviewSelected" type_name="gh_drawing_color" type_code="36">
              <ARGB>100;0;150;0</ARGB>
            </item>
          </items>
        </chunk>
        <chunk name="DefinitionProperties">
          <items count="3">
            <item name="Date" type_name="gh_date" type_code="8">638115567792076234</item>
            <item name="Description" type_name="gh_string" type_code="10"></item>
            <item name="Name" type_name="gh_string" type_code="10">unnamed</item>
          </items>
          <chunks count="3">
            <chunk name="Revisions">
              <items count="1">
                <item name="RevisionCount" type_name="gh_int32" type_code="3">0</item>
              </items>
            </chunk>
            <chunk name="Projection">
              <items count="2">
                <item name="Target" type_name="gh_drawing_point" type_code="30">
                  <X>1654</X>
                  <Y>138</Y>
                </item>
                <item name="Zoom" type_name="gh_single" type_code="5">1.38178146</item>
              </items>
            </chunk>
            <chunk name="Views">
              <items count="1">
                <item name="ViewCount" type_name="gh_int32" type_code="3">0</item>
              </items>
            </chunk>
          </chunks>
        </chunk>
        <chunk name="RcpLayout">
          <items count="1">
            <item name="GroupCount" type_name="gh_int32" type_code="3">0</item>
          </items>
        </chunk>
        <chunk name="GHALibraries">
          <items count="1">
            <item name="Count" type_name="gh_int32" type_code="3">1</item>
          </items>
          <chunks count="1">
            <chunk name="Library" index="0">
              <items count="6">
                <item name="AssemblyFullName" type_name="gh_string" type_code="10">BH.UI.Grasshopper, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null</item>
                <item name="AssemblyVersion" type_name="gh_string" type_code="10">6.0.0.0</item>
                <item name="Author" type_name="gh_string" type_code="10"></item>
                <item name="Id" type_name="gh_guid" type_code="9">8bbd9f31-e1cd-fb1a-4588-730892e8d0cf</item>
                <item name="Name" type_name="gh_string" type_code="10">BH.UI.Grasshopper</item>
                <item name="Version" type_name="gh_string" type_code="10">6.0.0.0</item>
              </items>
            </chunk>
          </chunks>
        </chunk>
        <chunk name="DefinitionObjects">
          <items count="1">
            <item name="ObjectCount" type_name="gh_int32" type_code="3">4</item>
          </items>
          <chunks count="4">
            <chunk name="Object" index="0">
              <items count="3">
                <item name="GUID" type_name="gh_guid" type_code="9">d45ad8e8-cf03-464c-ba89-2122f4c6e4fa</item>
                <item name="Lib" type_name="gh_guid" type_code="9">8bbd9f31-e1cd-fb1a-4588-730892e8d0cf</item>
                <item name="Name" type_name="gh_string" type_code="10">Execute</item>
              </items>
              <chunks count="1">
                <chunk name="Container">
                  <items count="5">
                    <item name="Component" type_name="gh_string" type_code="10"></item>
                    <item name="Description" type_name="gh_string" type_code="10">Adapter Action 'Execute': sends commands to be executed in an external software
</item>
                    <item name="InstanceGuid" type_name="gh_guid" type_code="9">b78f3e1e-7529-4de0-abca-e5170dd9abe5</item>
                    <item name="Name" type_name="gh_string" type_code="10">Execute</item>
                    <item name="NickName" type_name="gh_string" type_code="10">Execute</item>
                  </items>
                  <chunks count="2">
                    <chunk name="Attributes">
                      <items count="3">
                        <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                          <X>697</X>
                          <Y>155</Y>
                          <W>149</W>
                          <H>84</H>
                        </item>
                        <item name="Pivot" type_name="gh_drawing_pointf" type_code="31">
                          <X>783</X>
                          <Y>197</Y>
                        </item>
                        <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                      </items>
                    </chunk>
                    <chunk name="ParameterData">
                      <items count="8">
                        <item name="InputCount" type_name="gh_int32" type_code="3">4</item>
                        <item name="InputId" index="0" type_name="gh_guid" type_code="9">72194041-4e06-4e8c-bbeb-36fd484907e0</item>
                        <item name="InputId" index="1" type_name="gh_guid" type_code="9">ffe324e7-1fc0-4818-9fcb-43a0202cc974</item>
                        <item name="InputId" index="2" type_name="gh_guid" type_code="9">ffe324e7-1fc0-4818-9fcb-43a0202cc974</item>
                        <item name="InputId" index="3" type_name="gh_guid" type_code="9">cb95db89-6165-43b6-9c41-5702bc5bf137</item>
                        <item name="OutputCount" type_name="gh_int32" type_code="3">2</item>
                        <item name="OutputId" index="0" type_name="gh_guid" type_code="9">d67b6cf3-37ea-438e-a6b4-2cc76b572658</item>
                        <item name="OutputId" index="1" type_name="gh_guid" type_code="9">cb95db89-6165-43b6-9c41-5702bc5bf137</item>
                      </items>
                      <chunks count="6">
                        <chunk name="InputParam" index="0">
                          <items count="10">
                            <item name="Description" type_name="gh_string" type_code="10">Adapter to the external software
This is a BH.Adapter.BHoMAdapter</item>
                            <item name="InstanceGuid" type_name="gh_guid" type_code="9">afa3c9d9-6803-4ba2-8cb3-dc49dc1c2d57</item>
                            <item name="Name" type_name="gh_string" type_code="10">adapter</item>
                            <item name="NickName" type_name="gh_string" type_code="10">adapter</item>
                            <item name="ObjectType" type_name="gh_string" type_code="10">{ "_t" : "System.Type", "Name" : "BH.Adapter.BHoMAdapter, BHoM_Adapter, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null", "_bhomVersion" : "6.1" }</item>
                            <item name="Optional" type_name="gh_bool" type_code="1">false</item>
                            <item name="Source" index="0" type_name="gh_guid" type_code="9">1e0601c7-0c62-4530-82ff-330f79ba864d</item>
                            <item name="SourceCount" type_name="gh_int32" type_code="3">1</item>
                            <item name="m_ForcePreview" type_name="gh_bool" type_code="1">false</item>
                            <item name="m_MaxItemsPreview" type_name="gh_int32" type_code="3">10000</item>
                          </items>
                          <chunks count="1">
                            <chunk name="Attributes">
                              <items count="3">
                                <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                                  <X>699</X>
                                  <Y>157</Y>
                                  <W>69</W>
                                  <H>20</H>
                                </item>
                                <item name="Pivot" type_name="gh_drawing_pointf" type_code="31">
                                  <X>735</X>
                                  <Y>167</Y>
                                </item>
                                <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                              </items>
                            </chunk>
                          </chunks>
                        </chunk>
                        <chunk name="InputParam" index="1">
                          <items count="10">
                            <item name="Description" type_name="gh_string" type_code="10">Command to run
This is a BH.oM.Adapter.IExecuteCommand:
Classes implementing IExecuteCommand are commands compatible with the `Execute` Adapter Action.
This can be of the following types: DownloadCommand, RenameCommand, MoveCommand, CopyCommand, Bake, UpdateCommand, UpsertCommand, Transfer, SaveAs, Save, Open, NewModel, Exit, CustomCommand, Close, and more...</item>
                            <item name="InstanceGuid" type_name="gh_guid" type_code="9">387eabde-032d-4666-9a7c-f6f8204f3588</item>
                            <item name="Name" type_name="gh_string" type_code="10">command</item>
                            <item name="NickName" type_name="gh_string" type_code="10">command</item>
                            <item name="ObjectType" type_name="gh_string" type_code="10">{ "_t" : "System.Type", "Name" : "BH.oM.Adapter.IExecuteCommand", "_bhomVersion" : "6.1" }</item>
                            <item name="Optional" type_name="gh_bool" type_code="1">false</item>
                            <item name="Source" index="0" type_name="gh_guid" type_code="9">bd520e2c-0d2e-4e05-b9bb-b633237f8c1f</item>
                            <item name="SourceCount" type_name="gh_int32" type_code="3">1</item>
                            <item name="m_ForcePreview" type_name="gh_bool" type_code="1">false</item>
                            <item name="m_MaxItemsPreview" type_name="gh_int32" type_code="3">10000</item>
                          </items>
                          <chunks count="1">
                            <chunk name="Attributes">
                              <items count="3">
                                <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                                  <X>699</X>
                                  <Y>177</Y>
                                  <W>69</W>
                                  <H>20</H>
                                </item>
                                <item name="Pivot" type_name="gh_drawing_pointf" type_code="31">
                                  <X>735</X>
                                  <Y>187</Y>
                                </item>
                                <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                              </items>
                            </chunk>
                          </chunks>
                        </chunk>
                        <chunk name="InputParam" index="2">
                          <items count="9">
                            <item name="Description" type_name="gh_string" type_code="10">Configuration for this Action. You can input an ActionConfig (it contains the configs common to all Toolkits); 
consider that Toolkits may have a custom ActionConfig (e.g. GSAConfig, SpeckleConfig).
This is a BH.oM.Adapter.ActionConfig:
Configurations specific for an Adapter Action (Push, Pull, etc).
Consider that your tookit might have a more specific implementation available. Try to look for [your toolkit name]ActionConfig.</item>
                            <item name="InstanceGuid" type_name="gh_guid" type_code="9">f6bb31d8-0930-4d87-b3df-8e411769499e</item>
                            <item name="Name" type_name="gh_string" type_code="10">actionConfig</item>
                            <item name="NickName" type_name="gh_string" type_code="10">actionConfig</item>
                            <item name="ObjectType" type_name="gh_string" type_code="10">{ "_t" : "System.Type", "Name" : "BH.oM.Adapter.ActionConfig", "_bhomVersion" : "6.1" }</item>
                            <item name="Optional" type_name="gh_bool" type_code="1">true</item>
                            <item name="SourceCount" type_name="gh_int32" type_code="3">0</item>
                            <item name="m_ForcePreview" type_name="gh_bool" type_code="1">false</item>
                            <item name="m_MaxItemsPreview" type_name="gh_int32" type_code="3">10000</item>
                          </items>
                          <chunks count="1">
                            <chunk name="Attributes">
                              <items count="3">
                                <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                                  <X>699</X>
                                  <Y>197</Y>
                                  <W>69</W>
                                  <H>20</H>
                                </item>
                                <item name="Pivot" type_name="gh_drawing_pointf" type_code="31">
                                  <X>735</X>
                                  <Y>207</Y>
                                </item>
                                <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                              </items>
                            </chunk>
                          </chunks>
                        </chunk>
                        <chunk name="InputParam" index="3">
                          <items count="7">
                            <item name="Description" type_name="gh_string" type_code="10">Execute the command
This is a Boolean</item>
                            <item name="InstanceGuid" type_name="gh_guid" type_code="9">286a5941-3d47-4e7f-9e19-7c56ad3a0636</item>
                            <item name="Name" type_name="gh_string" type_code="10">active</item>
                            <item name="NickName" type_name="gh_string" type_code="10">active</item>
                            <item name="Optional" type_name="gh_bool" type_code="1">true</item>
                            <item name="Source" index="0" type_name="gh_guid" type_code="9">ff1c217a-b769-4e18-b549-cf14c6899e73</item>
                            <item name="SourceCount" type_name="gh_int32" type_code="3">1</item>
                          </items>
                          <chunks count="2">
                            <chunk name="Attributes">
                              <items count="3">
                                <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                                  <X>699</X>
                                  <Y>217</Y>
                                  <W>69</W>
                                  <H>20</H>
                                </item>
                                <item name="Pivot" type_name="gh_drawing_pointf" type_code="31">
                                  <X>735</X>
                                  <Y>227</Y>
                                </item>
                                <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                              </items>
                            </chunk>
                            <chunk name="PersistentData">
                              <items count="1">
                                <item name="Count" type_name="gh_int32" type_code="3">1</item>
                              </items>
                              <chunks count="1">
                                <chunk name="Branch" index="0">
                                  <items count="2">
                                    <item name="Count" type_name="gh_int32" type_code="3">1</item>
                                    <item name="Path" type_name="gh_string" type_code="10">{0}</item>
                                  </items>
                                  <chunks count="1">
                                    <chunk name="Item" index="0">
                                      <items count="1">
                                        <item name="boolean" type_name="gh_bool" type_code="1">false</item>
                                      </items>
                                    </chunk>
                                  </chunks>
                                </chunk>
                              </chunks>
                            </chunk>
                          </chunks>
                        </chunk>
                        <chunk name="OutputParam" index="0">
                          <items count="12">
                            <item name="Access" type_name="gh_int32" type_code="3">1</item>
                            <item name="Description" type_name="gh_string" type_code="10">Output of the executed command.
This is a Object</item>
                            <item name="InstanceGuid" type_name="gh_guid" type_code="9">6c41cc3b-b45d-468f-b158-1cc704e15bb4</item>
                            <item name="Name" type_name="gh_string" type_code="10">output</item>
                            <item name="NickName" type_name="gh_string" type_code="10">output</item>
                            <item name="ObjectType" type_name="gh_string" type_code="10">{ "_t" : "System.Type", "Name" : "System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089", "_bhomVersion" : "6.1" }</item>
                            <item name="Optional" type_name="gh_bool" type_code="1">true</item>
                            <item name="ScriptParamAccess" type_name="gh_int32" type_code="3">1</item>
                            <item name="SourceCount" type_name="gh_int32" type_code="3">0</item>
                            <item name="TypeHintID" type_name="gh_guid" type_code="9">6a184b65-baa3-42d1-a548-3915b401de53</item>
                            <item name="m_ForcePreview" type_name="gh_bool" type_code="1">false</item>
                            <item name="m_MaxItemsPreview" type_name="gh_int32" type_code="3">10000</item>
                          </items>
                          <chunks count="1">
                            <chunk name="Attributes">
                              <items count="3">
                                <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                                  <X>798</X>
                                  <Y>157</Y>
                                  <W>46</W>
                                  <H>40</H>
                                </item>
                                <item name="Pivot" type_name="gh_drawing_pointf" type_code="31">
                                  <X>821</X>
                                  <Y>177</Y>
                                </item>
                                <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                              </items>
                            </chunk>
                          </chunks>
                        </chunk>
                        <chunk name="OutputParam" index="1">
                          <items count="6">
                            <item name="Description" type_name="gh_string" type_code="10">True if the operation was successful.
This is a Boolean</item>
                            <item name="InstanceGuid" type_name="gh_guid" type_code="9">867af73c-87a2-4d8f-97be-9872e125ab6a</item>
                            <item name="Name" type_name="gh_string" type_code="10">success</item>
                            <item name="NickName" type_name="gh_string" type_code="10">success</item>
                            <item name="Optional" type_name="gh_bool" type_code="1">true</item>
                            <item name="SourceCount" type_name="gh_int32" type_code="3">0</item>
                          </items>
                          <chunks count="1">
                            <chunk name="Attributes">
                              <items count="3">
                                <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                                  <X>798</X>
                                  <Y>197</Y>
                                  <W>46</W>
                                  <H>40</H>
                                </item>
                                <item name="Pivot" type_name="gh_drawing_pointf" type_code="31">
                                  <X>821</X>
                                  <Y>217</Y>
                                </item>
                                <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                              </items>
                            </chunk>
                          </chunks>
                        </chunk>
                      </chunks>
                    </chunk>
                  </chunks>
                </chunk>
              </chunks>
            </chunk>
            <chunk name="Object" index="1">
              <items count="3">
                <item name="GUID" type_name="gh_guid" type_code="9">dd286cb5-2bc6-4c4a-aac5-542d1d0954b5</item>
                <item name="Lib" type_name="gh_guid" type_code="9">8bbd9f31-e1cd-fb1a-4588-730892e8d0cf</item>
                <item name="Name" type_name="gh_string" type_code="10">HTTPAdapter</item>
              </items>
              <chunks count="1">
                <chunk name="Container">
                  <items count="5">
                    <item name="Component" type_name="gh_string" type_code="10"></item>
                    <item name="Description" type_name="gh_string" type_code="10"></item>
                    <item name="InstanceGuid" type_name="gh_guid" type_code="9">a1e520bf-0264-4f67-8960-c2cc7f9939ac</item>
                    <item name="Name" type_name="gh_string" type_code="10">HTTPAdapter</item>
                    <item name="NickName" type_name="gh_string" type_code="10">HTTPAdapter</item>
                  </items>
                  <chunks count="2">
                    <chunk name="Attributes">
                      <items count="3">
                        <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                          <X>442</X>
                          <Y>90</Y>
                          <W>49</W>
                          <H>28</H>
                        </item>
                        <item name="Pivot" type_name="gh_drawing_pointf" type_code="31">
                          <X>456</X>
                          <Y>104</Y>
                        </item>
                        <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                      </items>
                    </chunk>
                    <chunk name="ParameterData">
                      <items count="3">
                        <item name="InputCount" type_name="gh_int32" type_code="3">0</item>
                        <item name="OutputCount" type_name="gh_int32" type_code="3">1</item>
                        <item name="OutputId" index="0" type_name="gh_guid" type_code="9">72194041-4e06-4e8c-bbeb-36fd484907e0</item>
                      </items>
                      <chunks count="1">
                        <chunk name="OutputParam" index="0">
                          <items count="9">
                            <item name="Description" type_name="gh_string" type_code="10">This is a BH.Adapter.HTTP.HTTPAdapter</item>
                            <item name="InstanceGuid" type_name="gh_guid" type_code="9">1e0601c7-0c62-4530-82ff-330f79ba864d</item>
                            <item name="Name" type_name="gh_string" type_code="10">H</item>
                            <item name="NickName" type_name="gh_string" type_code="10">H</item>
                            <item name="ObjectType" type_name="gh_string" type_code="10">{ "_t" : "System.Type", "Name" : "BH.Adapter.HTTP.HTTPAdapter, HTTP_Adapter, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null", "_bhomVersion" : "6.1" }</item>
                            <item name="Optional" type_name="gh_bool" type_code="1">false</item>
                            <item name="SourceCount" type_name="gh_int32" type_code="3">0</item>
                            <item name="m_ForcePreview" type_name="gh_bool" type_code="1">false</item>
                            <item name="m_MaxItemsPreview" type_name="gh_int32" type_code="3">10000</item>
                          </items>
                          <chunks count="1">
                            <chunk name="Attributes">
                              <items count="3">
                                <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                                  <X>471</X>
                                  <Y>92</Y>
                                  <W>18</W>
                                  <H>24</H>
                                </item>
                                <item name="Pivot" type_name="gh_drawing_pointf" type_code="31">
                                  <X>480</X>
                                  <Y>104</Y>
                                </item>
                                <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                              </items>
                            </chunk>
                          </chunks>
                        </chunk>
                      </chunks>
                    </chunk>
                  </chunks>
                </chunk>
              </chunks>
            </chunk>
            <chunk name="Object" index="2">
              <items count="2">
                <item name="GUID" type_name="gh_guid" type_code="9">2e78987b-9dfb-42a2-8b76-3923ac8bd91a</item>
                <item name="Name" type_name="gh_string" type_code="10">Boolean Toggle</item>
              </items>
              <chunks count="1">
                <chunk name="Container">
                  <items count="7">
                    <item name="Description" type_name="gh_string" type_code="10">Boolean (true/false) toggle</item>
                    <item name="InstanceGuid" type_name="gh_guid" type_code="9">ff1c217a-b769-4e18-b549-cf14c6899e73</item>
                    <item name="Name" type_name="gh_string" type_code="10">Boolean Toggle</item>
                    <item name="NickName" type_name="gh_string" type_code="10">Toggle</item>
                    <item name="Optional" type_name="gh_bool" type_code="1">false</item>
                    <item name="SourceCount" type_name="gh_int32" type_code="3">0</item>
                    <item name="ToggleValue" type_name="gh_bool" type_code="1">true</item>
                  </items>
                  <chunks count="1">
                    <chunk name="Attributes">
                      <items count="2">
                        <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                          <X>445</X>
                          <Y>280</Y>
                          <W>104</W>
                          <H>22</H>
                        </item>
                        <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                      </items>
                    </chunk>
                  </chunks>
                </chunk>
              </chunks>
            </chunk>
            <chunk name="Object" index="3">
              <items count="3">
                <item name="GUID" type_name="gh_guid" type_code="9">76221701-c5e7-4a93-8a2b-d34e77ed9cc1</item>
                <item name="Lib" type_name="gh_guid" type_code="9">8bbd9f31-e1cd-fb1a-4588-730892e8d0cf</item>
                <item name="Name" type_name="gh_string" type_code="10">ClearResults</item>
              </items>
              <chunks count="1">
                <chunk name="Container">
                  <items count="5">
                    <item name="Component" type_name="gh_string" type_code="10">{ "SelectedItem" : { "_t" : "System.Type", "Name" : "BH.oM.Adapter.Commands.ClearResults", "_bhomVersion" : "6.1" }, "InputParams" : [], "OutputParams" : [{ "_t" : "BH.oM.UI.ParamInfo", "BHoM_Guid" : "50a5820f-8a37-4944-9a72-8c5420cd8438", "Name" : "C", "Fragments" : [], "Tags" : [], "CustomData" : { }, "DataType" : { "_t" : "System.Type", "Name" : "BH.oM.Adapter.Commands.ClearResults", "_bhomVersion" : "6.1" }, "Description" : "This is a BH.oM.Adapter.Commands.ClearResults:\r\nUsed to instruct the external software to clear/delete results from a file or model.", "Kind" : "Output", "HasDefaultValue" : false, "DefaultValue" : null, "IsRequired" : true, "IsSelected" : true, "DefaultValueWarning" : "" }], "BHoM_Guid" : "d6504001-3066-44fb-8f78-41b6a47cfbe4", "_bhomVersion" : "6.1" }</item>
                    <item name="Description" type_name="gh_string" type_code="10">This is a BH.oM.Adapter.Commands.ClearResults:
Used to instruct the external software to clear/delete results from a file or model.</item>
                    <item name="InstanceGuid" type_name="gh_guid" type_code="9">6d58b386-366f-46d0-b4d3-6e1257bee2bb</item>
                    <item name="Name" type_name="gh_string" type_code="10">ClearResults</item>
                    <item name="NickName" type_name="gh_string" type_code="10">ClearResults</item>
                  </items>
                  <chunks count="2">
                    <chunk name="Attributes">
                      <items count="3">
                        <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                          <X>496</X>
                          <Y>212</Y>
                          <W>48</W>
                          <H>28</H>
                        </item>
                        <item name="Pivot" type_name="gh_drawing_pointf" type_code="31">
                          <X>510</X>
                          <Y>226</Y>
                        </item>
                        <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                      </items>
                    </chunk>
                    <chunk name="ParameterData">
                      <items count="3">
                        <item name="InputCount" type_name="gh_int32" type_code="3">0</item>
                        <item name="OutputCount" type_name="gh_int32" type_code="3">1</item>
                        <item name="OutputId" index="0" type_name="gh_guid" type_code="9">ffe324e7-1fc0-4818-9fcb-43a0202cc974</item>
                      </items>
                      <chunks count="1">
                        <chunk name="OutputParam" index="0">
                          <items count="9">
                            <item name="Description" type_name="gh_string" type_code="10">This is a BH.oM.Adapter.Commands.ClearResults:
Used to instruct the external software to clear/delete results from a file or model.</item>
                            <item name="InstanceGuid" type_name="gh_guid" type_code="9">bd520e2c-0d2e-4e05-b9bb-b633237f8c1f</item>
                            <item name="Name" type_name="gh_string" type_code="10">C</item>
                            <item name="NickName" type_name="gh_string" type_code="10">C</item>
                            <item name="ObjectType" type_name="gh_string" type_code="10">{ "_t" : "System.Type", "Name" : "BH.oM.Adapter.Commands.ClearResults", "_bhomVersion" : "6.1" }</item>
                            <item name="Optional" type_name="gh_bool" type_code="1">false</item>
                            <item name="SourceCount" type_name="gh_int32" type_code="3">0</item>
                            <item name="m_ForcePreview" type_name="gh_bool" type_code="1">false</item>
                            <item name="m_MaxItemsPreview" type_name="gh_int32" type_code="3">10000</item>
                          </items>
                          <chunks count="1">
                            <chunk name="Attributes">
                              <items count="3">
                                <item name="Bounds" type_name="gh_drawing_rectanglef" type_code="35">
                                  <X>525</X>
                                  <Y>214</Y>
                                  <W>17</W>
                                  <H>24</H>
                                </item>
                                <item name="Pivot" type_name="gh_drawing_pointf" type_code="31">
                                  <X>533.5</X>
                                  <Y>226</Y>
                                </item>
                                <item name="Selected" type_name="gh_bool" type_code="1">true</item>
                              </items>
                            </chunk>
                          </chunks>
                        </chunk>
                      </chunks>
                    </chunk>
                  </chunks>
                </chunk>
              </chunks>
            </chunk>
          </chunks>
        </chunk>
      </chunks>
    </chunk>
  </chunks>
</Archive>
</details>

### CODE REVIEW

**Review by rboulton-BH — APPROVED** [review]
Tested with the script as per screenshot. Error message appears as expected
image

**Review by FraserGreenroyd — APPROVED** [review]
Code changes make sense and bring the benefit described by the issue. Happy for this to be deployed following the hack session.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
