### PR TITLE
`ProcessObjectsForPush()` to first Unpack any `IContainer`, then check for IBHoMObjects

### LINKED ISSUE #350: `ProcessObjectsForPush` raises irrelevant warning when an `IContainer` is provided to the Push
#### Description:

When an `IContainer` is specified, the Push behaves correctly but an irrelevant warning is returned:
image

Fixable easily by changing the order of the checking and unpacking.

#### Steps to reproduce:

See above.

#### Expected behaviour:

No warning.

#### Test file(s):

See above.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #350
Closes #351

`ProcessObjectsForPush()` now first Unpacks any `IContainer`, then checks for IBHoMObjects.
This allows to wrap any unpacked non-BHoMObject if required; also, it removes non-relevant warning when an IContainer is provided (as `IContainer` does not implement `IBHoMObject`).

### Test file

See #350

### CODE REVIEW

**Review by IsakNaslundBh — APPROVED** [review]
Take it as this basically removes a warning for objects of type `IContainer` that are not inheriting from `BHoMObject`.

Cannot see how this really would have any bad impact on anything.

Code changes makes sense, and all UTs passing.

Happy to approve!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
