### PR TITLE
Update Copyright Header to 2021

### LINKED ISSUE #281: Compliance of BHoM file Copyright Headers
All BHoM `.cs` files need to contain the current [BHoM copyright statement](https://github.com/BHoM/BHoM/blob/master/COPYRIGHT_HEADER.txt) as their header.

For more information see [Code Compliance - HasValidCopyright](https://github.com/BHoM/documentation/wiki/HasValidCopyright)

### PR DESCRIPTION
**Pull request by BHoMBot**
Closes #281

### CODE REVIEW

**Review by alelom — APPROVED** [review]
LGTM.

**Comment by FraserGreenroyd** [comment]
@alelom as you're offline on Teams - can you make sure to add compliance tags to PRs you're merging if you're merging them before I get to look at them for the copyright stuff please :smile:

**Comment by alelom** [comment]
> @alelom as you're offline on Teams - can you make sure to add compliance tags to PRs you're merging if you're merging them before I get to look at them for the copyright stuff please 😄

Sorry, must be because I'm connected to another Teams organization (working on CIH). I think I re-enabled teams on my mobile so now I should be reachable there too.

**Pull request merged**
