### PR TITLE
Fix replace objects in loads module culling duplicates

### LINKED ISSUE #352: ReplaceObjectsInLoadsModule unintentionally removes objects with duplicate BHoM Guids
#### Description:

Some modify methods, such as Transform, might not update the Guid of the object being changed. This is due to the fact that the method may not know if you are moving the objects, or essentially copying it like arraying a set of bars up along each story)

The Replace method added in https://github.com/BHoM/BHoM_Adapter/pull/349 had the unintended side effect of culling duplicates based on BHoM_Guid - something that was not intended and should not happen.

#### Steps to reproduce:

Tranform the same for example Bar multiple times, and try to push them at the same time as any type of load. Only one (the first) of the arrayed bars will be pushed.

#### Expected behaviour:

For the replace objects to only try to replace if _all_ objects being pushed have unique Ids. If any duplicate Id is found, the method should exit and not modify anything.

_All_ objects being sent in to the method needs to be returned - no duplicate culling should be done!

#### Test file(s):

Have UT ready in the adapter test showcasing the issue.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #352

See issue for details

### Test files

Tests updated to showcase issues

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check versioning

**Review by alelom — APPROVED** [review]
Approved based on code changes and unit tests.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
