### PR TITLE
BHoM_Adapter: Adding Before and After methods for each action

### LINKED ISSUE #383: BHoM_Adapter: introduce "before" and "after" virtual methods for Adapter Actions
#### Description:

We can introduce a new feature justified by the increasing usage of downstream implementations of the BHoM Adapter from non-UI contexts – i.e. adapter code called from some other code (e.g. Excel_Adapter's Push being called from other Toolkits).

In these contexts, specific Actions (e.g. the Push) can happen to need some "preparation" and "teardown" activity. These activities typically need to be performed once per Action, but they need to be called programmatically when the Action is invoked programmatically.

For example, the Push from Excel. If called from the context of an UI, the Push will create a workbook, then write to it, then save the workbook. If the Push is called from another piece of code, however, you may have several lists of objects (a list of lists input) that you want to push. In this case, you are forced to call the push for each input list, which incurs in unneeded overhead for the workbook and saving creation per each list, which slows things down. Some workaround that essentially create objects to group have been attempted, but we may solve this by introducing optional overridable methods (see https://github.com/BHoM/Excel_Toolkit/pull/54 and its ["grouping" object](https://github.com/BHoM/Excel_Toolkit/pull/54/files#diff-834964006d4e77a7a5192bae45b5768138979af2a7aa670678882c36c81a1244)).

We can introduce the following `virtual` methods that are by default empty:
- `BeforePush`/`AfterPush`
- `BeforePull`/`AfterPull`
- ... etc. (same fore every action)

Each of these methods will have to take as inputs all of the inputs available to the main action. These methods can then be implemented as required by downstream toolkits. This addition won't affect existing downstream implementations.

These methods should be by default invoked by BHoM_UI just before and just after the Action method, that is, respectively at the last and at the first useful moment. This means e.g. `BeforePush()` should happen after any `SetupPushType()` and `SetupPushConfig()`, and `AfterPush()` should be called just after the call to the Push. See https://github.com/BHoM/BHoM_UI/blob/ae56ad7a7d2650bf99197e0ba864fb3abfc6be55/BHoM_UI/Components/Adapter/Push.cs#L89-L115

### PR DESCRIPTION
**Pull request by albinber**
### NOTE: Depends on 

Not directly dependant, but a related BHoM_UI PR uses these new methods, required for testing in the UI. 
https://github.com/BHoM/BHoM_UI/pull/481
   
### Issues addressed by this PR

Closes #383

Introducing "before" and "after" methods for adapter actions following discussion between @FraserGreenroyd and @alelom.

### CODE REVIEW

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Following discussion with @alelom, can we add, to each description (including the other additional methods within each file), the following sentence:

`This method is intended to be called by the context in which this Adapter is run, which typically is a UI supported by BHoM.`

**Comment by albinber** [comment]
@BHoMBot check required

**Review by alelom — APPROVED** [review]
Thanks for these changes, which I believe will make adapters more flexible.

The code changes look good, and they work (tested with the File_Adapter test scripts).

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by FraserGreenroyd — APPROVED** [review]
Looks great on code review, thanks @albinber 😄

**Pull request merged**
