### PR TITLE
Handle nulls in Adapter_Engine methods

### LINKED ISSUE #297: Handle nulls
In the following methods:

 - [x] BH.Engine.Adapter.Query.AdapterIds(IBHoMObject bHoMObject, Type adapterIdFragmentType)
 - [x] BH.Engine.Adapter.Query.HasAdapterIdFragment(IBHoMObject iBHoMObject, Type fragmentType)
 - [x] BH.Engine.Adapter.Query.GetFullFileName(FileSettings fileSettings)
 - [x] BH.Engine.Adapter.Modify.SetAdapterId(IBHoMObject bHoMObject, IAdapterId id)

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #297

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Review by alelom — APPROVED** [review]
Looks good and tested from Interop perspective.

Would be good to have a comment from structures too @IsakNaslundBh

**Comment by FraserGreenroyd** [comment]
On the basis of @IsakNaslundBh resourcing I'm thinking it might be best to merge @alelom and get it included in alphas for testing ASAP so we don't end up leaving it too long and get too close to the beta before we merge and get wider testing than just you and @IsakNaslundBh ?

**Comment by alelom** [comment]
@FraserGreenroyd Sounds good.

**Pull request merged**
