### PR TITLE
BHoM_Adapter: adding method to unpack objects provided in Push

### LINKED ISSUE #177: Common approach to pushing/pulling meta objects
#### Description:

Would be good to define a common approach (if there isn't one already!) to exchanging larger objects, those that contain many elements etc. We have a multistorey object and a truss object which have lists of elements, at the moment these need to be unwrapped in the UI and pushed. The short-term/easy option is to simply add another convert, but I wonder if there's a meta tag, or series of interfaces that let us categorize a bit further, then unwrap methods in the adapter to dispatch to relevant converts.

### PR DESCRIPTION
**Pull request by alelom**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Engine/pull/3001
   
### Issues addressed by this PR

Closes https://github.com/BHoM/BHoM_Adapter/issues/341
Closes #177

### Test files

See provided test project. We still do not have a concrete class that implements `IContainer` -- a test one is present in the test project.

### CODE REVIEW

**Review by IsakNaslundBh — APPROVED** [review]
Happy with this.

UT works fine, and have also tested with other example object and Robot_Toolkit, which works as expected.

Code changes also makes sense. Approved

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: ready-to-merge, project-compliance

**Pull request merged**
