### PR TITLE
Set up CI

### LINKED ISSUE #161: BHoM_Adapter: Prepare for CI
Prepare this repo for CI checks.

FYI: @alelom I know you're looking forward to this :wink:

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #161

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@al-fisher this is now ready for review :smile:

**Comment by alelom** [comment]
Something wrong here? 17h?
image

**Comment by FraserGreenroyd** [comment]
> Something wrong here? 17h?
> image

That test will never run, the pipeline was removed and won't show up in future PRs :smile:

**Pull request merged**
