### PR TITLE
BHoM_Adapter - Issues 43/45/63 - Refresh Interface for the adapter : config, params and error log

### LINKED ISSUE #43: BHoM_Adapter: Review the ErrorLog in the light of the Global error system
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

### LINKED ISSUE #45: BHoM_Adapter: use IExecuteParams interface for the Execute command -- enable as config option
To enable more flexible config.

Move the AdapterConfig to the BHoM and make it a BHoMObject

### LINKED ISSUE #63: BHoM_Adapter: Replace the Dictionary used for config by an interface
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

### PR DESCRIPTION
**Pull request by adecler**
Fixes #43.
Fixes #45.
Fixes #63.

Depends on https://github.com/BHoM/BHoM/pull/361 and (not really) on https://github.com/BHoM/BHoM_Engine/pull/736.

I would also have liked to take care of #32 but it seems that this one might need more than cosmetic changes so I left it be for now.

My strategy for this change is to use a single `CrudConfig` object as interface regardless of the type of crud operation being done. The reason for this is to avoid the headache of going from Push/Pull/etc configs to Create/Read/etc configs in a way that is not completely confusing for everyone. This is not an interface because it already has the Replace vs UpdateOnly property expected by the generic adapter.

The GitHub_Toolkit i a nice one to test the benefits of this new approach since it is the only one that I know that really makes use of the config. Unfortunately, there is already a pull request on the repo so I'll jut show you the code here in comments below.

Other than the need to modify the interface of every single adapter, the changes needed are really small. here's the list of manipulation we have on the config currently (only repos for OS listed):
- RevitAdapter: 
	- Just create config if null but not used
- GSA_Toolkit: 
	- Execute is using parameters dictionary
- Robot_Toolkit: 
	- Execute is using parameters dictionary
- Mongo_Toolkit: 
	- Execute is using parameters and config dictionary
	- Push is using config for Tag and Replace
	
- BHoM_UI:
	- Need to change the interface for all CRUD components
- Dynamo_Toolkit: 
	- Execute old method is doing some preporcessing (Method_Basilisk/CRUD/Execute)
	- Same for UpdateProperty, Delete, Move, Pull, Push
- Grasshoper_Toolkit
	- SolveInstance of old components are collectiong dictionaries for all CRUD config
	
Note that we should not change the interface of the old UI components to avoid losing compatibility. Those components can just be modified sightly internally to produce a CrudConfig from the dictionary given how little that config was used anyway.

I have marked this PR for the 2.1 milestone since I think the change should happen soon but it shouldn't necessarily be for the OS deadline. What do you think?

### CODE REVIEW

**Comment by rwemay** [comment]
@adecler , speaking to @IsakNaslundBh , we think this branch/PR is now superseded/other developments have overtaken. Can we close this now and delete the branch?

**Comment by al-fisher** [comment]
Yep - thanks @rwemay 
Following good workshops last week - @adecler @alelom - do perhaps do a final review and close and delete branch when happy now

**Comment by alelom** [comment]
I was just now in the process of reviewing what could be saved of this / if anything overlaps with the current proposals. Especially with regards to the `config` which we did not cover much in our chats.
I'll take care of removing this as soon as I think it's not useful anymore. Thanks!

**Comment by al-fisher** [comment]
Awesome! Thanks @alelom

**Comment by alelom** [comment]
After some consideration, I think I will take a hint from this parked branch with regards to the `config` paramter, as illustrated [here](https://github.com/BHoM/BHoM_Adapter/issues/108).

**Pull request closed without merging**
