### PR TITLE
Update Assembly Version

### LINKED ISSUE #237: Update AssemblyFileVersion
The `AssemblyFileVersion` attribute should now be updated to read `3.3.0.0` for all `AssemblyInfo.cs` files within this repository for the start of the 3.3 milestone

### PR DESCRIPTION
**Pull request by BHoMBot**
Closes #237

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@alelom can this be looked at soonish please? :smile:

**Comment by al-fisher** [comment]
Closing this PR - without merging as this commit has been included in [this PR](https://github.com/BHoM/BHoM_Adapter/pull/243)  as [this commit](https://github.com/BHoM/BHoM_Adapter/pull/243/commits/09aa0882561b58201fb45e0ad3642f3ec76f19d4)

**Pull request closed without merging**
