### PR TITLE
Fix incorrect null check on Tag prior to Push via FullCRUD

### LINKED ISSUE #326: BHoM_Adapter: Tag check bug adds null tag to tags before push
#### Description:
AN additional null tag is added to objects before pushing.

#### Steps to reproduce:
Push any object and debug the FullCRUD method, and note the null tag added due to an errant tag check.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #326

Fix an incorrect null check on tags. There was no guard against null values.

### Test files

See https://github.com/BHoM/BHoM_Adapter/issues/326

### CODE REVIEW

**Comment by enarhi** [comment]
LGTM, tested with [script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Adapter/%23326-NullTagCheckBug?csf=1&web=1&e=MS0dG7) where the null tag was causing a failed push and the push now works as expected.

**Review by enarhi — APPROVED** [review]
LGTM, tested with [script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Adapter/%23326-NullTagCheckBug?csf=1&web=1&e=MS0dG7) where the null tag was causing a failed push and the push now works as expected.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
Code change is sensible given the issue described and this should resolve it.

**Pull request merged**
