### PR TITLE
BHoM_Adapter: Implement Issue Templates on Repos

### LINKED ISSUE #104: BHoM_Adapter: implement issue templates
Implement issue templates.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR
Added github templates in .github/ISSUE_TEMPLATE

Closes #104 

### Test files
No test file needed.

### CODE REVIEW

**Comment by alelom** [comment]
> LGTM!
> 
> Sorry... stealing your acronym!

That's ok I think I stole it from Eduardo, he might be the most hurt

**Comment by FraserGreenroyd** [comment]
> > LGTM!
> > Sorry... stealing your acronym!
> 
> That's ok I think I stole it from Eduardo, he might be the most hurt

In that case sorry @epignatelli ! But it's a good one for quick PRs like this :smile:

**Comment by epignatelli** [comment]
> > > LGTM!
> > > Sorry... stealing your acronym!
> > 
> > 
> > That's ok I think I stole it from Eduardo, he might be the most hurt
> 
> In that case sorry @epignatelli ! But it's a good one for quick PRs like this 😄

ahahah That's actually behavioural heritage from the good old [lgtm pull-request approval system](https://github.com/lgtmco/lgtm/wiki)

**Comment by alelom** [comment]
@al-fisher we do not have merge rights, could you please merge? :)

**Comment by al-fisher** [comment]
Done - thanks @alelom!

**Pull request merged**
