### PR TITLE
Upgrade BHoM_Adapter to .Net Standard 2.0

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/1292
https://github.com/BHoM/BHoM_Engine/pull/2634

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by IsakNaslundBh — APPROVED** [review]
LGTM!

Compiles with structural adapters, and all tested with them. All looks fine

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check documentation-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check ready-to-merge

**Pull request merged**
